### ISSUE TITLE
Store page doesn't work + how do I install games?

### ISSUE THREAD

**Issue by techsideofficial** [real-pmein1/stmsrvemu#18]
<img width="742" alt="image" src="https://github.com/real-pmein1/stmsrvemu/assets/68258126/69bfb571-3632-4c4b-abc0-c93ec97c6974">
How to install games like the orange box, and what is the product key for games?

**Comment by real-pmein1** [comment]
The store websites aren't included in the project and are being worked on separately.  The project is also to provide a way to run old versions of Steam; you need to have app storages in the appropriate locations in order to download games.  You can find some details within the readme that should guide you in the right direction.
